version: '3.9'

services:
  server:
    build: ./server
    container_name: express-server
    ports:
      - 4000:4000
    networks:
      - fullstack-app

  client:
    build: ./client
    container_name: react-client
    ports:
      - 5174:3000
    networks:
      - fullstack-app
    depends_on:
      - server


networks:
  fullstack-app:
    driver: bridge